In [2]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

In [3]:
from src.ingestion.musicbrainz_client import MusicBrainzClient
import json
client = MusicBrainzClient()
result = client.search_artist("NewJeans")
print(json.dumps(result, indent=2))

https://musicbrainz.org/ws/2/artist
{
  "created": "2026-07-08T04:34:47.883Z",
  "count": 6,
  "offset": 0,
  "artists": [
    {
      "id": "49204a7a-ed85-407a-828f-6fd46f1d8126",
      "type": "Group",
      "type-id": "e431f5f6-b5d2-343d-8b36-72607fffb74b",
      "score": 100,
      "name": "NewJeans",
      "sort-name": "NewJeans",
      "country": "KR",
      "area": {
        "id": "b9f7d640-46e8-313e-b158-ded6d18593b3",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
        "name": "South Korea",
        "sort-name": "South Korea",
        "life-span": {
          "ended": null
        }
      },
      "begin-area": {
        "id": "aa03e165-4c73-4959-91c0-a99f9fa8ecab",
        "type": "City",
        "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
        "name": "Seoul",
        "sort-name": "Seoul",
        "life-span": {
          "ended": null
        }
      },
      "ipis": [
        "00022979958"
      ],
      "isnis": [
        "0000000507844940"
      ],
      "life-span": {
        "begin": "2022-07-22",
        "ended": null
      },
      "aliases": [
        {
          "sort-name": "NJZ",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\uc5d4\uc81c\uc774\uc9c0",
          "locale": "ko",
          "type": "Artist name",
          "primary": null,
          "begin-date": "2025-02",
          "end-date": "2025"
        },
        {
          "sort-name": "NJZ",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "NJZ",
          "locale": "en",
          "type": "Artist name",
          "primary": null,
          "begin-date": "2025-02",
          "end-date": "2025"
        },
        {
          "sort-name": "NewJeans",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\u30cb\u30e5\u30fc\u30b8\u30fc\u30f3\u30ba",
          "locale": "ja",
          "type": "Artist name",
          "primary": null,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "NewJeans",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\ub274\uc9c4\uc2a4",
          "locale": "ko",
          "type": "Artist name",
          "primary": null,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "NWJNS",
          "type-id": "1937e404-b981-3cb7-8151-4c86ebfc8d8e",
          "name": "NWJNS",
          "locale": null,
          "type": "Search hint",
          "primary": null,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "New Jeans",
          "type-id": "1937e404-b981-3cb7-8151-4c86ebfc8d8e",
          "name": "New Jeans",
          "locale": null,
          "type": "Search hint",
          "primary": null,
          "begin-date": null,
          "end-date": null
        }
      ],
      "tags": [
        {
          "count": 2,
          "name": "kpop"
        },
        {
          "count": 5,
          "name": "girl group"
        },
        {
          "count": 9,
          "name": "k-pop"
        },
        {
          "count": 0,
          "name": "r&b"
        },
        {
          "count": 0,
          "name": "future bass"
        },
        {
          "count": 2,
          "name": "4th gen k-pop"
        },
        {
          "count": 1,
          "name": "throwback sound"
        }
      ]
    },
    {
      "id": "dae456c7-7acd-4d14-9402-42d8b78efc7b",
      "type": "Person",
      "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
      "score": 58,
      "gender-id": "93452b5a-a947-30c8-934f-6a4056b151c2",
      "name": "Danielle",
      "sort-name": "Danielle",
      "gender": "female",
      "country": "KR",
      "area": {
        "id": "b9f7d640-46e8-313e-b158-ded6d18593b3",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
        "name": "South Korea",
        "sort-name": "South Korea",
        "life-span": {
          "ended": null
        }
      },
      "begin-area": {
        "id": "4983a5b8-eb24-431e-a782-93bec2a56fdc",
        "type": "City",
        "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
        "name": "Newcastle",
        "sort-name": "Newcastle",
        "life-span": {
          "ended": null
        }
      },
      "disambiguation": "NewJeans",
      "life-span": {
        "begin": "2005-04-11",
        "ended": null
      },
      "aliases": [
        {
          "sort-name": "Marsh, Danielle",
          "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
          "name": "Danielle Marsh",
          "locale": "en",
          "type": "Legal name",
          "primary": null,
          "begin-date": "2005-04-11",
          "end-date": null
        },
        {
          "sort-name": "Danielle",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\ub2e4\ub2c8\uc5d8",
          "locale": "ko",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Danielle",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\u30c0\u30cb\u30a8\u30eb",
          "locale": "ja",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Danielle",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "Danielle",
          "locale": "en",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Mo, Ji-hye",
          "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
          "name": "\ubaa8\uc9c0\ud61c",
          "locale": "ko_KR",
          "type": "Legal name",
          "primary": null,
          "begin-date": null,
          "end-date": null
        }
      ]
    },
    {
      "id": "3902653d-ec22-4a74-8909-90ee509d1a39",
      "type": "Person",
      "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
      "score": 57,
      "gender-id": "93452b5a-a947-30c8-934f-6a4056b151c2",
      "name": "\ud61c\uc778",
      "sort-name": "Hyein",
      "gender": "female",
      "country": "KR",
      "area": {
        "id": "b9f7d640-46e8-313e-b158-ded6d18593b3",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
        "name": "South Korea",
        "sort-name": "South Korea",
        "life-span": {
          "ended": null
        }
      },
      "begin-area": {
        "id": "805deaa9-f30c-4856-baa4-19f206df64ce",
        "type": "City",
        "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
        "name": "Incheon",
        "sort-name": "Incheon",
        "life-span": {
          "ended": null
        }
      },
      "disambiguation": "NewJeans",
      "life-span": {
        "begin": "2008-04-21",
        "ended": null
      },
      "aliases": [
        {
          "sort-name": "Hyein",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\u30d8\u30a4\u30f3",
          "locale": "ja",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Hyein",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "Hyein",
          "locale": "en",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Hyein",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\ud61c\uc778",
          "locale": "ko",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Lee, Hyein",
          "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
          "name": "\uc774\ud61c\uc778",
          "locale": "ko",
          "type": "Legal name",
          "primary": null,
          "begin-date": "2008-04-21",
          "end-date": null
        }
      ]
    },
    {
      "id": "3c777558-ad56-47f0-add8-1177a6321553",
      "type": "Person",
      "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
      "score": 57,
      "gender-id": "93452b5a-a947-30c8-934f-6a4056b151c2",
      "name": "\ubbfc\uc9c0",
      "sort-name": "Minji",
      "gender": "female",
      "country": "KR",
      "area": {
        "id": "b9f7d640-46e8-313e-b158-ded6d18593b3",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
        "name": "South Korea",
        "sort-name": "South Korea",
        "life-span": {
          "ended": null
        }
      },
      "begin-area": {
        "id": "70f18007-b179-497c-982c-64621e9ad0c3",
        "type": "Municipality",
        "type-id": "17246454-5ac4-36a1-b81a-4753eb2dab20",
        "name": "Yeongwol",
        "sort-name": "Yeongwol",
        "life-span": {
          "ended": null
        }
      },
      "disambiguation": "NewJeans",
      "life-span": {
        "begin": "2004-05-07",
        "ended": null
      },
      "aliases": [
        {
          "sort-name": "Minji",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\u30df\u30f3\u30b8",
          "locale": "ja",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Minji",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "Minji",
          "locale": "en",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Minji",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\ubbfc\uc9c0",
          "locale": "ko",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Kim, Minji",
          "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
          "name": "\uae40\ubbfc\uc9c0",
          "locale": "ko",
          "type": "Legal name",
          "primary": null,
          "begin-date": "2004-05-07",
          "end-date": null
        }
      ]
    },
    {
      "id": "6ab2ecdd-1045-4120-bd96-2441c0f52ae1",
      "type": "Person",
      "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
      "score": 57,
      "gender-id": "93452b5a-a947-30c8-934f-6a4056b151c2",
      "name": "Hanni",
      "sort-name": "Hanni",
      "gender": "female",
      "country": "KR",
      "area": {
        "id": "b9f7d640-46e8-313e-b158-ded6d18593b3",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
        "name": "South Korea",
        "sort-name": "South Korea",
        "life-span": {
          "ended": null
        }
      },
      "begin-area": {
        "id": "b4e9352c-8edf-4911-8fa3-e852afa30501",
        "type": "City",
        "type-id": "6fd8f29a-3d0a-32fc-980d-ea697b69da78",
        "name": "Melbourne",
        "sort-name": "Melbourne",
        "life-span": {
          "ended": null
        }
      },
      "disambiguation": "NewJeans",
      "life-span": {
        "begin": "2004-10-06",
        "ended": null
      },
      "aliases": [
        {
          "sort-name": "H\u00e2n, Ph\u1ea1m Ng\u1ecdc",
          "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
          "name": "Ph\u1ea1m Ng\u1ecdc H\u00e2n",
          "locale": "vi",
          "type": "Legal name",
          "primary": null,
          "begin-date": "2004-10-06",
          "end-date": null
        },
        {
          "sort-name": "Hanni",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\u30cf\u30cb",
          "locale": "ja",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Hanni",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "Hanni",
          "locale": "en",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Hanni",
          "type-id": "894afba6-2816-3c24-8072-eadb66bd04bc",
          "name": "\ud558\ub2c8",
          "locale": "ko",
          "type": "Artist name",
          "primary": true,
          "begin-date": null,
          "end-date": null
        },
        {
          "sort-name": "Pham, Hanni",
          "type-id": "d4dcd0c0-b341-3612-a332-c0ce797b25cf",
          "name": "Hanni Pham",
          "locale": "en",
          "type": "Legal name",
          "primary": null,
          "begin-date": "2004-10-06",
          "end-date": null
        }
      ]
    },
    {
      "id": "98be0695-56d4-4da8-8d0c-87d83d5ecd55",
      "type": "Person",
      "type-id": "b6e035f4-3ce9-331c-97df-83397230b0df",
      "score": 48,
      "name": "Gigi",
      "sort-name": "Gigi",
      "country": "KR",
      "area": {
        "id": "b9f7d640-46e8-313e-b158-ded6d18593b3",
        "type": "Country",
        "type-id": "06dd0ae4-8c74-30bb-b43d-95dcedf961de",
        "name": "South Korea",
        "sort-name": "South Korea",
        "life-span": {
          "ended": null
        }
      },
      "disambiguation": "lyricist associated with NewJeans",
      "life-span": {
        "ended": null
      }
    }
  ]
}

In [6]:
# result = client.get_artist("49204a7a-ed85-407a-828f-6fd46f1d8126", inc="artist-rels")
# print(result)

In [5]:
mb_client = MusicBrainzClient()

In [1]:
# njz_id = "49204a7a-ed85-407a-828f-6fd46f1d8126"
# result = mb_client.get_artist(njz_id, inc="release-groups")

In [8]:
# result = mb_client.search_artist("Hyukoh")
# for a in result['artists'][:5]:
#     print(f"{a['name']} — score: {a['score']} — type: {a.get('type', '?')}")

In [4]:
hyukoh_search = mb_client.search_artist("Hyukoh")
hyukoh_id = hyukoh_search['artists'][0]['id']

hyukoh_detail = mb_client.get_artist(hyukoh_id, inc="tags")
print(hyukoh_detail.get('tags', 'No tags found'))

https://musicbrainz.org/ws/2/artist

ReadTimeout: HTTPSConnectionPool(host='musicbrainz.org', port=443): Read timed out. (read timeout=30)

In [13]:
result = mb_client.search_artist("Blur")
for a in result['artists'][:5]:
    print(f"{a['name']} — score: {a['score']} — type: {a.get('type', '?')}")

https://musicbrainz.org/ws/2/artist
Blur — score: 100 — type: Group
Hooverian Blur — score: 69 — type: Person
Flex Blur — score: 69 — type: ?
Inside Blur — score: 68 — type: ?
Rosco Blur — score: 67 — type: ?

In [14]:
# blur_id = result['artists'][0]['id']
# print(blur_id)

# detail = mb_client.get_artist(blur_id, inc="tags")
# print(detail.get('tags', 'No tags found'))

In [6]:
for name in ["Nirvana", "Smashing Pumpkins", "Pearl Jam", "Soundgarden", "Blur", "Deftones"]:
    search_result = mb_client.search_artist(name)
    top_match = search_result['artists'][0]
    print(f"{name} -> {top_match['name']} (score: {top_match['score']}, id: {top_match['id']})")

https://musicbrainz.org/ws/2/artist
Nirvana -> Nirvana (score: 100, id: 5b11f4ce-a62d-471e-81fc-a69a8278c7da)
https://musicbrainz.org/ws/2/artist
Smashing Pumpkins -> The Smashing Pumpkins (score: 100, id: ba0d6274-db14-4ef5-b28d-657ebde1a396)
https://musicbrainz.org/ws/2/artist
Pearl Jam -> Pearl Jam (score: 100, id: 83b9cbe7-9857-49e2-ab8e-b57b01038103)
https://musicbrainz.org/ws/2/artist
Soundgarden -> Soundgarden (score: 100, id: 153c9281-268f-4cf3-8938-f5a4593e5df4)
https://musicbrainz.org/ws/2/artist
Blur -> Blur (score: 100, id: ba853904-ae25-4ebb-89d6-c44cfbd71bd2)
https://musicbrainz.org/ws/2/artist
Deftones -> Deftones (score: 100, id: 7527f6c2-d762-4b88-b5e2-9244f1e34c46)

In [7]:
seed_artists = ["Nirvana", "Smashing Pumpkins", "Pearl Jam", "Soundgarden", "Blur", "Deftones"]
os.makedirs("../data/raw/artists", exist_ok=True)

for name in seed_artists:
    print(f"\n⏳ [1/3] Mencari ID untuk: {name}...")
    search_result = mb_client.search_artist(name)
    artist_id = search_result['artists'][0]['id']
    
    print(f"🔍 [2/3] ID ditemukan ({artist_id}). Sedang download data raksasa (ini mungkin agak lama)...")
    detail = mb_client.get_artist(artist_id, inc="artist-rels+release-groups+tags")
    
    filepath = f"../data/raw/artists/{artist_id}.json"
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(detail, f, indent=2, ensure_ascii=False)
    
    print(f"✅ [3/3] Sukses tersimpan: {detail['name']} -> {filepath}")

⏳ [1/3] Mencari ID untuk: Nirvana...
https://musicbrainz.org/ws/2/artist
🔍 [2/3] ID ditemukan (5b11f4ce-a62d-471e-81fc-a69a8278c7da). Sedang download data raksasa (ini mungkin agak lama)...
✅ [3/3] Sukses tersimpan: Nirvana -> ../data/raw/artists/5b11f4ce-a62d-471e-81fc-a69a8278c7da.json

⏳ [1/3] Mencari ID untuk: Smashing Pumpkins...
https://musicbrainz.org/ws/2/artist
🔍 [2/3] ID ditemukan (ba0d6274-db14-4ef5-b28d-657ebde1a396). Sedang download data raksasa (ini mungkin agak lama)...

ReadTimeout: HTTPSConnectionPool(host='musicbrainz.org', port=443): Read timed out. (read timeout=30)

In [8]:
seed_ids = {
    "5b11f4ce-a62d-471e-81fc-a69a8278c7da": "Nirvana",
    "ba0d6274-db14-4ef5-b28d-657ebde1a396": "The Smashing Pumpkins",
    "83b9cbe7-9857-49e2-ab8e-b57b01038103": "Pearl Jam",
    "153c9281-268f-4cf3-8938-f5a4593e5df4": "Soundgarden",
    "ba853904-ae25-4ebb-89d6-c44cfbd71bd2": "Blur",
    "7527f6c2-d762-4b88-b5e2-9244f1e34c46": "Deftones",        
}

raw_dir = "../data/raw/artists"

for filename in os.listdir(raw_dir):
    filepath = os.path.join(raw_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        artist_data = json.load(f)

    for rel in artist_data.get("relations", []):
        target = rel.get("artist")
        if target and target["id"] in seed_ids:
            print(f"{artist_data['name']} --[{rel['type']}]--> {target['name']}")

In [9]:
from collections import defaultdict

person_to_bands = defaultdict(set)

for filename in os.listdir(raw_dir):
    filepath = os.path.join(raw_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        artist_data = json.load(f)

    band_name = artist_data['name']

    for rel in artist_data.get("relations", []):
        target = rel.get("artist")
        if target and target.get("type") == "Person":
            person_to_bands[target["name"]].add(band_name)

for person, bands in person_to_bands.items():
    if len(bands) > 1:
        print(f"{person} -> {bands}")

Matt Cameron -> {'Soundgarden', 'Pearl Jam'}
Jason Everman -> {'Soundgarden', 'Nirvana'}

In [10]:
import pandas as pd

raw_dir = "../data/raw/artists"
rows = []

for filename in os.listdir(raw_dir):
    filepath = os.path.join(raw_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        artist = json.load(f)

    tags = artist.get("tags", [])
    top_tags = sorted(tags, key=lambda t: t["count"], reverse=True)[:3]
    top_tag_names = [t["name"] for t in top_tags]

    rows.append({
        "mbid": artist.get("id"),
        "name": artist.get("name"),
        "type": artist.get("type"),
        "country": artist.get("country"),
        "begin_date": artist.get("life-span", {}).get("begin"),
        "num_relations": len(artist.get("relations", [])),
        "num_release_groups": len(artist.get("release-groups", [])),
        "top_tags": ", ".join(top_tag_names)
    })

df = pd.DataFrame(rows)
df

,mbid,name,type,country,begin_date,num_relations,num_release_groups,top_tags
0,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,Group,US,1984,13,25,"grunge, alternative rock, alternative metal"
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,Group,US,1987,45,25,"grunge, alternative rock, rock"
2,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,Group,US,1988,10,25,"alternative metal, nu metal, alternative rock"
3,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,Group,US,1990,41,25,"grunge, alternative rock, rock"
4,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,Group,US,1988,21,25,"alternative rock, dream pop, neo-psychedelia"
5,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,Group,GB,1990,13,25,"alternative rock, britpop, indie rock"

In [11]:
print(df['name'].tolist())

['Soundgarden', 'Nirvana', 'Deftones', 'Pearl Jam', 'The Smashing Pumpkins', 'Blur']

In [10]:
TSP_id = df[df['name'] == 'The Smashing Pumpkins']['mbid'].values[0]
recordings = client.get_artist_recordings(TSP_id, limit=10)
print(json.dumps(recordings, indent=2))

{
  "recording-offset": 0,
  "recording-count": 14797,
  "recordings": [
    {
      "id": "16b49f80-2998-48fc-8b1b-61727df005aa",
      "video": false,
      "length": 171467,
      "disambiguation": "live, 2016\u201004\u201005: Beacon Theatre, New York, NY, USA",
      "title": "\u201cIntroduce the Band\u201d (banter)"
    },
    {
      "id": "3248e640-2a1a-4be6-814e-de4dee2d0a20",
      "video": false,
      "length": 34400,
      "disambiguation": "live, 1996-06-15: Golden Gate Park, San Francisco, CA, USA",
      "first-release-date": "1996",
      "title": "\u2018Hello\u2019"
    },
    {
      "length": 511000,
      "video": false,
      "disambiguation": "live, 2007\u201007\u201028: The Fillmore, San Francisco, CA, USA",
      "id": "3634b60a-a9fa-428f-83e7-16c033aa5f88",
      "title": "\u201cAmp Meltdown\u201d (banter)"
    },
    {
      "video": false,
      "disambiguation": "live, 1998-07-29: DAR Constitution Hall, Washington, DC, USA",
      "length": 159294,
      "id": "4f39aa2a-b4c7-4ed8-8621-52f6d5cc3d9b",
      "title": "\u2018City Lights School Check Presentation\u2019 (banter)"
    },
    {
      "id": "57e3a886-2d83-4ab5-88ee-76dc88951ef3",
      "video": false,
      "length": 189000,
      "disambiguation": "",
      "first-release-date": "1996-11-26",
      "title": "...Said Sadly"
    },
    {
      "title": "- DJ (intro)",
      "video": false,
      "length": 26096,
      "disambiguation": "",
      "id": "b4bfeaa4-09ed-4e2b-9524-380efd2f8aae"
    },
    {
      "title": "\u201cLame Showbiz Tactics\u201d",
      "id": "ba5bc99b-ce85-4822-aa17-1b35fdf17f85",
      "length": 63000,
      "video": false,
      "disambiguation": "live, 2000-05-06: Sunrise Theater, Sunrise, FL, USA"
    },
    {
      "title": "\"Love Gun\" Tease (intro)",
      "video": false,
      "length": 36179,
      "disambiguation": "",
      "id": "bca52f0b-3403-4315-9a30-e918dd530643"
    },
    {
      "disambiguation": "",
      "video": false,
      "length": 191000,
      "id": "e0435b57-ec6e-4a2a-be89-2aed220bad99",
      "title": "\u2026Said Sadly",
      "first-release-date": "1995-10-23"
    },
    {
      "title": "\u201cHello, Hello, Hello!\u201d",
      "video": false,
      "disambiguation": "live, 2000-05-06: Sunrise Theater, Sunrise, FL, USA",
      "length": 39000,
      "id": "fbe1203a-7364-4a8c-9488-b7b186b0bf26"
    }
  ]
}

In [14]:
smashing_pumpkins_id = "ba0d6274-db14-4ef5-b28d-657ebde1a396"

with open(f"../data/raw/artists/{smashing_pumpkins_id}.json", "r", encoding="utf-8") as f:
    sp_data = json.load(f)

release_groups = sp_data["release-groups"]
print(f"Total release-groups: {len(release_groups)}")

Total release-groups: 25

In [15]:
clean_albums = [
    rg for rg in release_groups
    if rg.get("primary-type") == "Album" and not rg.get("secondary-types")
]

print(f"Clean studio albums: {len(clean_albums)}")
for album in clean_albums:
    print(f"- {album['title']} ({album.get('first-release-date', 'unknown')})")

Clean studio albums: 14
- Gish (1991-05-28)
- Siamese Dream (1993-07-26)
- Mellon Collie and the Infinite Sadness (1995-10-23)
- Adore (1998-05-29)
- MACHINA/the machines of God (1999-11)
- Machina II/the friends and enemies of modern music (2000-09-05)
- Zeitgeist (2007-07-06)
- Oceania (2012-06-18)
- Monuments to an Elegy (2014-12-05)
- SHINY AND OH SO BRIGHT, VOL. 1 / LP: NO PAST. NO FUTURE. NO SUN. (2018-11-16)
- CYR (2020-11-27)
- ATUM: A Rock Opera in Three Acts (2022-11-15)
- Zodeon at Crystal Hall (2023)
- Aghori Mhori Mei (2024-08-02)

In [16]:
siamese_dream = next(a for a in clean_albums if a['title'] == 'Siamese Dream')
rg_id = siamese_dream['id']

releases = client.get_releases_from_group(rg_id)
print(f"Number of releases (editions): {releases['release-count']}")
for r in releases['releases'][:5]:
    print(f"- {r['title']} | date: {r.get('date')} | country: {r.get('country')}")

Number of releases (editions): 33
- Siamese Dream | date: 1993-07-26 | country: GB
- Siamese Dream | date: 2011-12-02 | country: None
- Siamese Dream | date: 2007 | country: US
- Siamese Dream | date: 2011-11-29 | country: US
- Siamese Dream | date: 2011-11-29 | country: US

In [12]:
release_id = releases["releases"][0]["id"]

release_detail = client.get_release(
    release_id,
    inc="recordings+media+artist-credits+labels"
)

release_detail.keys()

NameError: name 'releases' is not defined

In [ ]:
media = release_detail.get("media", [])
print(f"Number of discs/media: {len(media)}")

for disc in media:
    print(f"\nFormat: {disc.get('format')}, Track count: {disc.get('track-count')}")
    
   
    for track in disc.get("tracks", []):
    
        recording = track.get("recording", {})
        recording_id = recording.get("id", "Unknown ID")
        length_ms = track.get("length", "Unknown")
        
        print(f"  {track['position']}. {track['title']} — {length_ms}ms [Recording ID: {recording_id}]")

Number of discs/media: 1

Format: CD, Track count: 13
  1. Cherub Rock — 298133ms [Recording ID: 40a1bdab-d6cc-4116-8cdb-736979854503]
  2. Quiet — 221960ms [Recording ID: 199069ef-ff18-48a7-95f3-caaa9ee20b10]
  3. Today — 199933ms [Recording ID: 622baf54-342a-40a6-801e-43f159fc4f38]
  4. Hummer — 417106ms [Recording ID: af02bd48-8c3a-4e9b-b9d2-6a21e6bcf32d]
  5. Rocket — 246893ms [Recording ID: 69d9ab4e-8beb-4bf6-b22b-7ee71d2a9bcf]
  6. Disarm — 197200ms [Recording ID: 99479876-9f93-45b8-8e84-caef39f69d4d]
  7. Soma — 399933ms [Recording ID: 7f76d520-bdfa-48e1-9966-2fe8330c6245]
  8. Geek U.S.A. — 313866ms [Recording ID: ea714e98-6a99-4bca-b38a-a69ea34b5da4]
  9. Mayonaise — 349173ms [Recording ID: ed3bfa34-7b15-4853-b777-0daf549dedd8]
  10. Spaceboy — 268600ms [Recording ID: 46c88b2c-7788-4bf3-880e-0b77155c2f84]
  11. Silverfuck — 523466ms [Recording ID: 79666748-d0f7-4f8a-806e-6c8419345069]
  12. Sweet Sweet — 98933ms [Recording ID: a40e20b0-b08f-4657-8d15-57ead3408736]
  13. Luna — 200600ms [Recording ID: 7d4b6488-d906-4d23-89f8-b6ca8fd8b843]

In [13]:
rows = []

for medium in release_detail["media"]:
    medium_format = medium.get("format")

    for track in medium.get("tracks", []):
        recording = track.get("recording", {})

        rows.append({
            "artist_id": smashing_pumpkins_id,
            "artist_name": "The Smashing Pumpkins",
            "release_group_id": rg_id,
            "release_group_title": siamese_dream["title"],
            "release_id": release_detail.get("id"),
            "release_title": release_detail.get("title"),
            "release_date": release_detail.get("date"),
            "country": release_detail.get("country"),
            "medium_format": medium_format,
            "track_position": track.get("position"),
            "track_title": track.get("title"),
            "recording_id": recording.get("id"),
            "length_ms": track.get("length"),
        })

album_tracks_df = pd.DataFrame(rows)
album_tracks_df

NameError: name 'release_detail' is not defined

In [ ]:
album_tracks_df.to_csv(
    "../data/processed/album_tracks_sample.csv",
    index=False
)

In [19]:
from src.preprocessing.release_preprocessor import release_to_track_rows

rows = release_to_track_rows(
    release_detail=release_detail,
    artist_id=smashing_pumpkins_id,
    artist_name="The Smashing Pumpkins",
    release_group_id=rg_id,
    release_group_title=siamese_dream["title"]
)

pd.DataFrame(rows)

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
0,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,1,Cherub Rock,40a1bdab-d6cc-4116-8cdb-736979854503,298133
1,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,2,Quiet,199069ef-ff18-48a7-95f3-caaa9ee20b10,221960
2,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,3,Today,622baf54-342a-40a6-801e-43f159fc4f38,199933
3,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,4,Hummer,af02bd48-8c3a-4e9b-b9d2-6a21e6bcf32d,417106
4,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,5,Rocket,69d9ab4e-8beb-4bf6-b22b-7ee71d2a9bcf,246893
5,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,6,Disarm,99479876-9f93-45b8-8e84-caef39f69d4d,197200
6,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,7,Soma,7f76d520-bdfa-48e1-9966-2fe8330c6245,399933
7,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,8,Geek U.S.A.,ea714e98-6a99-4bca-b38a-a69ea34b5da4,313866
8,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,9,Mayonaise,ed3bfa34-7b15-4853-b777-0daf549dedd8,349173
9,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,10,Spaceboy,46c88b2c-7788-4bf3-880e-0b77155c2f84,268600
10,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,11,Silverfuck,79666748-d0f7-4f8a-806e-6c8419345069,523466
11,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,12,Sweet Sweet,a40e20b0-b08f-4657-8d15-57ead3408736,98933
12,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,a159e102-18bb-42ca-a59e-5f96a7eff241,Siamese Dream,0dcb4610-006e-35a3-8575-3fee0fa1bb83,Siamese Dream,1993-07-26,GB,CD,13,Luna,7d4b6488-d906-4d23-89f8-b6ca8fd8b843,200600

In [14]:
from src.preprocessing.release_preprocessor import release_to_track_rows, pick_best_release

all_rows = []

seed_artist_map = {
    "Nirvana": "5b11f4ce-a62d-471e-81fc-a69a8278c7da",
    "The Smashing Pumpkins": "ba0d6274-db14-4ef5-b28d-657ebde1a396",
    "Pearl Jam": "83b9cbe7-9857-49e2-ab8e-b57b01038103",
    "Soundgarden": "153c9281-268f-4cf3-8938-f5a4593e5df4",
    "Blur": "ba853904-ae25-4ebb-89d6-c44cfbd71bd2",
    "Deftones": "7527f6c2-d762-4b88-b5e2-9244f1e34c46",
}

for artist_name, artist_id in seed_artist_map.items():
    try:
        with open(f"../data/raw/artists/{artist_id}.json", "r", encoding="utf-8") as f:
            artist_data = json.load(f)

        clean_albums = [
            rg for rg in artist_data["release-groups"]
            if rg.get("primary-type") == "Album" and not rg.get("secondary-types")
        ]

        if not clean_albums:
            print(f"{artist_name}: no clean albums, skipping")
            continue

        chosen_album = clean_albums[0]

        releases = client.get_releases_from_group(chosen_album["id"])
        best_release = pick_best_release(releases)

        if best_release is None:
            print(f"{artist_name}: no suitable release found, skipping")
            continue

        release_detail = client.get_release(best_release["id"], inc="recordings+media+artist-credits+labels")

        rows = release_to_track_rows(
            release_detail=release_detail,
            artist_id=artist_id,
            artist_name=artist_name,
            release_group_id=chosen_album["id"],
            release_group_title=chosen_album["title"]
        )

        all_rows.extend(rows)
        print(f"{artist_name}: {len(rows)} tracks added from '{chosen_album['title']}' ({best_release.get('date')})")

    except Exception as e:
        print(f"{artist_name}: FAILED - {e}")
        continue

album_tracks_df = pd.DataFrame(all_rows)
album_tracks_df

Nirvana: 13 tracks added from 'Bleach' (1989)
The Smashing Pumpkins: 10 tracks added from 'Gish' (1991)
Pearl Jam: 11 tracks added from 'Ten' (1991)
Soundgarden: 13 tracks added from 'Ultramega OK' (1988-10-31)
Blur: FAILED - HTTPSConnectionPool(host='musicbrainz.org', port=443): Read timed out. (read timeout=30)
Deftones: 11 tracks added from 'Adrenaline' (1995-10-02)

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
0,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,1,Blew,2837e0d2-5ce9-44da-803e-797c835d672c,174133.0
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,2,Floyd the Barber,4cce1ee1-38e6-4ea0-8584-b6ebeb854d7d,137973.0
2,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,3,About a Girl,b2e623ea-378b-4479-bb75-fa202aacbfc9,168293.0
3,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,4,School,0b3292f6-8f0d-4160-92d3-49348029a619,162173.0
4,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,5,Love Buzz,1adfecb7-875f-4203-b3b1-8e2e643f94a2,215093.0
5,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,6,Paper Cuts,67930d52-5e75-4c00-b36f-ee3c43bed160,245840.0
6,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,7,Negative Creep,06745db3-a2bc-4131-8a9d-0cbdc25b494a,175693.0
7,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,8,Scoff,dbecedb1-2a90-43fc-add4-ce4016676545,250133.0
8,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,9,Swap Meet,c9972a41-2ae8-43f6-9822-ba2fec7e50d1,182973.0
9,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,10,Mr. Moustache,6cd0083c-e4ce-4745-aaf0-704ab1de988a,203893.0
10,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,11,Sifting,25bbbd76-5f48-4b37-9722-44a346c4f3a9,322240.0
11,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,12,Big Cheese,c498c2ac-a571-412e-a26e-f37e86a1edda,222160.0
12,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,13,Downer,6011093f-704a-46b0-8941-ae2bee94d70a,102640.0
13,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,1,I Am One,3095b75c-ca7c-45f7-881d-41d6ab78063f,246973.0
14,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,2,Siva,df3fdb51-d9f6-489e-8bbc-6826aa490bad,263026.0
15,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,3,Rhinoceros,c14cc283-80da-40f8-a838-b880ccbcf50a,390506.0
16,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,4,Bury Me,acb2170b-a90b-4ed9-9df0-00f864347870,288400.0
17,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,5,Crush,9c4a05d3-ef63-40d6-82da-ceab7b1c421b,214760.0
18,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,6,Suffer,d283e46e-28e3-4d0c-96f0-4c67089a97a3,311266.0
19,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,7,Snail,d611c71c-0551-4083-abfe-89426c80dab4,311000.0
20,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,8,Tristessa,90c44add-190e-4cc6-89db-ae9b9aeea745,213600.0
21,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,9,Window Paine,b3b0764b-9ccb-43fd-bb61-37abdcf0c051,351706.0
22,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,10,Daydream / I'm Going Crazy,39c23d3b-0e9c-4a78-8017-398d78668c37,187760.0
23,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",1,Once,94bed552-376f-492d-8e87-f470aa7fda0c,231893.0
24,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",2,Even Flow,cccf8dde-f822-4981-b534-16e36c62de88,293600.0
25,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",3,Alive,c8ecea4a-b955-416d-866b-c218a73fa588,341200.0
26,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",4,Why Go,1778d1fa-cd04-4ac4-ac40-d467d41e2190,199906.0
27,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",5,Black,35cbb45d-0b40-415e-9301-f43fec4e1497,343666.0
28,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",6,Jeremy,d141baa5-ad5d-4893-aa9e-ae50d6c117bf,319360.0
29,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",7,Oceans,36d62268-a2ad-472f-99e1-bc338470f2d5,161666.0
30,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",8,Porch,39dcbb7e-3432-4a0c-972d-4c036da466fb,210533.0
31,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",9,Garden,1ba7114e-c6fc-4988-aaba-e6ff22ed1a29,298973.0
32,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",10,Deep,1226999c-e94e-49a0-94a1-3028d99b2883,258266.0
33,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",11,Release,d42f73ee-68c4-4c4d-9dbc-206979c53e7d,NaN
34,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,1,Flower,be4ff980-f829-4f88-9e11-ee13dc64bb31,209573.0
35,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,2,All Your Lies,53b1151c-1961-42b3-a9f2-7c9a06d1347c,231893.0
36,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,3,665,6f229429-5d7c-45aa-8132-fc7c06d035f8,97306.0
37,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,4,Beyond the Wheel,290c4ffa-c9ad-48d2-8f59-1a8b5f408af0,261893.0
38,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,5,667,76403253-216c-4ce4-93f6-15dbb61d56e4,64306.0
39,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,6,Mood for Trouble,1a7d73b4-4f41-48d5-844c-1eb110eb5218,265560.0
40,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,7,Circle of Power,8e34a142-8714-4edb-917d-8561793507c2,126306.0
41,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,8,He Didn’t,ee7fc943-1ad9-4187-a0b2-94f0388b2619,170800.0
42,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,9,Smokestack Lightning,9348d3fe-ffe2-496a-9125-5243ac503db0,307693.0
43,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,10,Nazi Driver,0f3e259a-86c9-401c-a510-fce8ac25073c,237906.0
44,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,11,Head Injury,95df1efa-798a-4344-a813-57a0393da387,146293.0
45,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,12,Incessant Mace,bba066fa-7f5d-477a-9a1d-4bf98df7d4dc,387106.0
46,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,13,One Minute of Silence,10e9a58a-4574-49d0-a319-4f4ab2c9bcf5,61866.0
47,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,1,Bored,02a5e8e3-2b6e-4c58-b4c1-cf54532c6dce,246360.0
48,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,2,Minus Blindfold,fd3c748f-64b4-4ff6-b7de-d6793de0c62d,244306.0
49,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,3,One Weak,011697a8-ea3d-4c4f-8a75-2b703decf1f0,268893.0
50,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,4,Nosebleed,1da70975-2cbe-49e8-abc1-3fba89e26dc3,266106.0
51,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,5,Lifter,2f183e18-7b41-44dd-8f95-2a1f142cf840,283026.0
52,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,6,Root,2258241d-9037-4cf6-915b-f354dc6b49f5,221066.0
53,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,7,7 Words,3e146264-5159-48e5-8940-db20aa99f482,223866.0
54,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,8,Birthmark,c409b0f2-29c4-4d89-aaa5-21e8f3c8f1fc,258506.0
55,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,9,Engine No. 9,cd9311bb-3713-4ef1-b394-b54f7d8eeb95,205226.0
56,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,10,Fireal,9dab0525-0ae3-40c1-9ea4-649579c7dce7,395573.0
57,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,11,Fist,879ccf75-15db-420f-b568-4b256474bd12,215400.0

In [24]:
failed_artists = {
    "The Smashing Pumpkins": "ba0d6274-db14-4ef5-b28d-657ebde1a396",
    "Pearl Jam": "83b9cbe7-9857-49e2-ab8e-b57b01038103",
    "Blur": "ba853904-ae25-4ebb-89d6-c44cfbd71bd2",
    "Deftones": "7527f6c2-d762-4b88-b5e2-9244f1e34c46",
}

for artist_name, artist_id in failed_artists.items():
    try:
        with open(f"../data/raw/artists/{artist_id}.json", "r", encoding="utf-8") as f:
            artist_data = json.load(f)

        clean_albums = [
            rg for rg in artist_data["release-groups"]
            if rg.get("primary-type") == "Album" and not rg.get("secondary-types")
        ]
        chosen_album = clean_albums[0]

        releases = client.get_releases_from_group(chosen_album["id"])
        best_release = pick_best_release(releases)

        release_detail = client.get_release(best_release["id"], inc="recordings+media+artist-credits+labels")

        rows = release_to_track_rows(
            release_detail=release_detail,
            artist_id=artist_id,
            artist_name=artist_name,
            release_group_id=chosen_album["id"],
            release_group_title=chosen_album["title"]
        )

        all_rows.extend(rows)
        print(f"{artist_name}: {len(rows)} tracks added from '{chosen_album['title']}' ({best_release.get('date')})")

    except Exception as e:
        print(f"{artist_name}: FAILED again - {e}")
        continue

The Smashing Pumpkins: 10 tracks added from 'Gish' (1991)
Pearl Jam: 11 tracks added from 'Ten' (1991)
Blur: FAILED again - HTTPSConnectionPool(host='musicbrainz.org', port=443): Read timed out. (read timeout=30)
Deftones: 11 tracks added from 'Adrenaline' (1995-10-02)

In [27]:
import time
time.sleep(10)  # kasih napas 10 detik dulu

blur_id = "ba853904-ae25-4ebb-89d6-c44cfbd71bd2"

with open(f"../data/raw/artists/{blur_id}.json", "r", encoding="utf-8") as f:
    blur_data = json.load(f)

clean_albums = [
    rg for rg in blur_data["release-groups"]
    if rg.get("primary-type") == "Album" and not rg.get("secondary-types")
]
chosen_album = clean_albums[0]

releases = client.get_releases_from_group(chosen_album["id"])
print("Success!")

Success!

In [28]:
best_release = pick_best_release(releases)

release_detail = client.get_release(best_release["id"], inc="recordings+media+artist-credits+labels")

rows = release_to_track_rows(
    release_detail=release_detail,
    artist_id=blur_id,
    artist_name="Blur",
    release_group_id=chosen_album["id"],
    release_group_title=chosen_album["title"]
)

all_rows.extend(rows)
print(f"Blur: {len(rows)} tracks added from '{chosen_album['title']}' ({best_release.get('date')})")

Blur: 12 tracks added from 'Leisure' (1991)

In [29]:
album_tracks_df = pd.DataFrame(all_rows)
album_tracks_df.to_csv("../data/processed/album_tracks.csv", index=False)
album_tracks_df

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
0,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,1,Blew,2837e0d2-5ce9-44da-803e-797c835d672c,174133.0
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,2,Floyd the Barber,4cce1ee1-38e6-4ea0-8584-b6ebeb854d7d,137973.0
2,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,3,About a Girl,b2e623ea-378b-4479-bb75-fa202aacbfc9,168293.0
3,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,4,School,0b3292f6-8f0d-4160-92d3-49348029a619,162173.0
4,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,5,Love Buzz,1adfecb7-875f-4203-b3b1-8e2e643f94a2,215093.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,8,Fool,5234f29d-777c-480b-bb47-d42c922a80ac,195333.0
66,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,9,Come Together,27090003-009c-4337-a648-7483c36bbfff,232400.0
67,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,10,High Cool,c3820526-1b1d-4852-b8ee-9fb909ddafb0,217626.0
68,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,11,Birthday,0b9b5669-eef0-420a-b695-350b36219c62,230000.0
69,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,12,Wear Me Down,a4f6872f-ff57-476c-8897-3ddc52d2169b,289333.0