In [2]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

In [3]:
from src.ingestion.musicbrainz_client import MusicBrainzClient
import json

In [4]:
mb_client = MusicBrainzClient()

In [5]:
for name in ["Nirvana", "Smashing Pumpkins", "Pearl Jam", "Soundgarden", "Blur", "Deftones"]:
    search_result = mb_client.search_artist(name)
    top_match = search_result['artists'][0]
    print(f"{name} -> {top_match['name']} (score: {top_match['score']}, id: {top_match['id']})")

https://musicbrainz.org/ws/2/artist
Nirvana -> Nirvana (score: 100, id: 5b11f4ce-a62d-471e-81fc-a69a8278c7da)
https://musicbrainz.org/ws/2/artist
Smashing Pumpkins -> The Smashing Pumpkins (score: 100, id: ba0d6274-db14-4ef5-b28d-657ebde1a396)
https://musicbrainz.org/ws/2/artist
Pearl Jam -> Pearl Jam (score: 100, id: 83b9cbe7-9857-49e2-ab8e-b57b01038103)
https://musicbrainz.org/ws/2/artist
Soundgarden -> Soundgarden (score: 100, id: 153c9281-268f-4cf3-8938-f5a4593e5df4)
https://musicbrainz.org/ws/2/artist
Blur -> Blur (score: 100, id: ba853904-ae25-4ebb-89d6-c44cfbd71bd2)
https://musicbrainz.org/ws/2/artist
Deftones -> Deftones (score: 100, id: 7527f6c2-d762-4b88-b5e2-9244f1e34c46)

In [6]:
seed_ids = {
    "5b11f4ce-a62d-471e-81fc-a69a8278c7da": "Nirvana",
    "ba0d6274-db14-4ef5-b28d-657ebde1a396": "The Smashing Pumpkins",
    "83b9cbe7-9857-49e2-ab8e-b57b01038103": "Pearl Jam",
    "153c9281-268f-4cf3-8938-f5a4593e5df4": "Soundgarden",
    "ba853904-ae25-4ebb-89d6-c44cfbd71bd2": "Blur",
    "7527f6c2-d762-4b88-b5e2-9244f1e34c46": "Deftones",        
}

raw_dir = "../data/raw/artists"

for filename in os.listdir(raw_dir):
    filepath = os.path.join(raw_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        artist_data = json.load(f)

    for rel in artist_data.get("relations", []):
        target = rel.get("artist")
        if target and target["id"] in seed_ids:
            print(f"{artist_data['name']} --[{rel['type']}]--> {target['name']}")

In [7]:
from collections import defaultdict

person_to_bands = defaultdict(set)

for filename in os.listdir(raw_dir):
    filepath = os.path.join(raw_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        artist_data = json.load(f)

    band_name = artist_data['name']

    for rel in artist_data.get("relations", []):
        target = rel.get("artist")
        if target and target.get("type") == "Person":
            person_to_bands[target["name"]].add(band_name)

for person, bands in person_to_bands.items():
    if len(bands) > 1:
        print(f"{person} -> {bands}")

Matt Cameron -> {'Soundgarden', 'Pearl Jam'}
Jason Everman -> {'Soundgarden', 'Nirvana'}

In [8]:
import pandas as pd

raw_dir = "../data/raw/artists"
rows = []

for filename in os.listdir(raw_dir):
    filepath = os.path.join(raw_dir, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        artist = json.load(f)

    tags = artist.get("tags", [])
    top_tags = sorted(tags, key=lambda t: t["count"], reverse=True)[:3]
    top_tag_names = [t["name"] for t in top_tags]

    rows.append({
        "mbid": artist.get("id"),
        "name": artist.get("name"),
        "type": artist.get("type"),
        "country": artist.get("country"),
        "begin_date": artist.get("life-span", {}).get("begin"),
        "num_relations": len(artist.get("relations", [])),
        "num_release_groups": len(artist.get("release-groups", [])),
        "top_tags": ", ".join(top_tag_names)
    })

df = pd.DataFrame(rows)
df

,mbid,name,type,country,begin_date,num_relations,num_release_groups,top_tags
0,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,Group,US,1984,13,25,"grunge, alternative rock, alternative metal"
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,Group,US,1987,45,25,"grunge, alternative rock, rock"
2,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,Group,US,1988,10,25,"alternative metal, nu metal, alternative rock"
3,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,Group,US,1990,41,25,"grunge, alternative rock, rock"
4,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,Group,US,1988,21,25,"alternative rock, dream pop, neo-psychedelia"
5,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,Group,GB,1990,13,25,"alternative rock, britpop, indie rock"

In [9]:
print(df['name'].tolist())

['Soundgarden', 'Nirvana', 'Deftones', 'Pearl Jam', 'The Smashing Pumpkins', 'Blur']

In [12]:
from src.preprocessing.release_preprocessor import release_to_track_rows, pick_best_release

all_rows = []

seed_artist_map = {
    "Nirvana": "5b11f4ce-a62d-471e-81fc-a69a8278c7da",
    "The Smashing Pumpkins": "ba0d6274-db14-4ef5-b28d-657ebde1a396",
    "Pearl Jam": "83b9cbe7-9857-49e2-ab8e-b57b01038103",
    "Soundgarden": "153c9281-268f-4cf3-8938-f5a4593e5df4",
    "Blur": "ba853904-ae25-4ebb-89d6-c44cfbd71bd2",
    "Deftones": "7527f6c2-d762-4b88-b5e2-9244f1e34c46",
}

for artist_name, artist_id in seed_artist_map.items():
    try:
        with open(f"../data/raw/artists/{artist_id}.json", "r", encoding="utf-8") as f:
            artist_data = json.load(f)

        clean_albums = [
            rg for rg in artist_data["release-groups"]
            if rg.get("primary-type") == "Album" and not rg.get("secondary-types")
        ]

        if not clean_albums:
            print(f"{artist_name}: no clean albums, skipping")
            continue

        chosen_album = clean_albums[0]

        releases = mb_client.get_releases_from_group(chosen_album["id"])
        best_release = pick_best_release(releases)

        if best_release is None:
            print(f"{artist_name}: no suitable release found, skipping")
            continue

        release_detail = mb_client.get_release(best_release["id"], inc="recordings+media+artist-credits+labels")

        rows = release_to_track_rows(
            release_detail=release_detail,
            artist_id=artist_id,
            artist_name=artist_name,
            release_group_id=chosen_album["id"],
            release_group_title=chosen_album["title"]
        )

        all_rows.extend(rows)
        print(f"{artist_name}: {len(rows)} tracks added from '{chosen_album['title']}' ({best_release.get('date')})")

    except Exception as e:
        print(f"{artist_name}: FAILED - {e}")
        continue

album_tracks_df = pd.DataFrame(all_rows)
album_tracks_df

Nirvana: 13 tracks added from 'Bleach' (1989)
The Smashing Pumpkins: FAILED - HTTPSConnectionPool(host='musicbrainz.org', port=443): Read timed out. (read timeout=30)
Pearl Jam: 11 tracks added from 'Ten' (1991)
Soundgarden: 13 tracks added from 'Ultramega OK' (1988-10-31)
Blur: 12 tracks added from 'Leisure' (1991)
Deftones: 11 tracks added from 'Adrenaline' (1995-10-02)

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
0,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,1,Blew,2837e0d2-5ce9-44da-803e-797c835d672c,174133.0
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,2,Floyd the Barber,4cce1ee1-38e6-4ea0-8584-b6ebeb854d7d,137973.0
2,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,3,About a Girl,b2e623ea-378b-4479-bb75-fa202aacbfc9,168293.0
3,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,4,School,0b3292f6-8f0d-4160-92d3-49348029a619,162173.0
4,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,5,Love Buzz,1adfecb7-875f-4203-b3b1-8e2e643f94a2,215093.0
5,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,6,Paper Cuts,67930d52-5e75-4c00-b36f-ee3c43bed160,245840.0
6,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,7,Negative Creep,06745db3-a2bc-4131-8a9d-0cbdc25b494a,175693.0
7,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,8,Scoff,dbecedb1-2a90-43fc-add4-ce4016676545,250133.0
8,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,9,Swap Meet,c9972a41-2ae8-43f6-9822-ba2fec7e50d1,182973.0
9,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,10,Mr. Moustache,6cd0083c-e4ce-4745-aaf0-704ab1de988a,203893.0
10,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,11,Sifting,25bbbd76-5f48-4b37-9722-44a346c4f3a9,322240.0
11,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,12,Big Cheese,c498c2ac-a571-412e-a26e-f37e86a1edda,222160.0
12,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,13,Downer,6011093f-704a-46b0-8941-ae2bee94d70a,102640.0
13,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",1,Once,94bed552-376f-492d-8e87-f470aa7fda0c,231893.0
14,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",2,Even Flow,cccf8dde-f822-4981-b534-16e36c62de88,293600.0
15,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",3,Alive,c8ecea4a-b955-416d-866b-c218a73fa588,341200.0
16,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",4,Why Go,1778d1fa-cd04-4ac4-ac40-d467d41e2190,199906.0
17,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",5,Black,35cbb45d-0b40-415e-9301-f43fec4e1497,343666.0
18,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",6,Jeremy,d141baa5-ad5d-4893-aa9e-ae50d6c117bf,319360.0
19,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",7,Oceans,36d62268-a2ad-472f-99e1-bc338470f2d5,161666.0
20,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",8,Porch,39dcbb7e-3432-4a0c-972d-4c036da466fb,210533.0
21,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",9,Garden,1ba7114e-c6fc-4988-aaba-e6ff22ed1a29,298973.0
22,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",10,Deep,1226999c-e94e-49a0-94a1-3028d99b2883,258266.0
23,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",11,Release,d42f73ee-68c4-4c4d-9dbc-206979c53e7d,NaN
24,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,1,Flower,be4ff980-f829-4f88-9e11-ee13dc64bb31,209573.0
25,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,2,All Your Lies,53b1151c-1961-42b3-a9f2-7c9a06d1347c,231893.0
26,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,3,665,6f229429-5d7c-45aa-8132-fc7c06d035f8,97306.0
27,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,4,Beyond the Wheel,290c4ffa-c9ad-48d2-8f59-1a8b5f408af0,261893.0
28,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,5,667,76403253-216c-4ce4-93f6-15dbb61d56e4,64306.0
29,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,6,Mood for Trouble,1a7d73b4-4f41-48d5-844c-1eb110eb5218,265560.0
30,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,7,Circle of Power,8e34a142-8714-4edb-917d-8561793507c2,126306.0
31,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,8,He Didn’t,ee7fc943-1ad9-4187-a0b2-94f0388b2619,170800.0
32,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,9,Smokestack Lightning,9348d3fe-ffe2-496a-9125-5243ac503db0,307693.0
33,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,10,Nazi Driver,0f3e259a-86c9-401c-a510-fce8ac25073c,237906.0
34,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,11,Head Injury,95df1efa-798a-4344-a813-57a0393da387,146293.0
35,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,12,Incessant Mace,bba066fa-7f5d-477a-9a1d-4bf98df7d4dc,387106.0
36,153c9281-268f-4cf3-8938-f5a4593e5df4,Soundgarden,ea22eb82-c3b2-32c6-84cf-10f7e28b0230,Ultramega OK,0d810c50-c79c-4f73-9ba7-6eb3ea0791f8,Ultramega OK,1988-10-31,US,CD,13,One Minute of Silence,10e9a58a-4574-49d0-a319-4f4ab2c9bcf5,61866.0
37,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,1,She’s So High,1c14202a-2ea7-4aff-bc41-6c97eb8a45e8,284733.0
38,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,2,Bang,2460e0f7-17c3-4a9f-a555-e20fea6b17a0,217933.0
39,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,3,Slow Down,31e589f5-4ed0-45d0-ac00-ef16b612f4a7,191266.0
40,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,4,Repetition,ca5c9d27-0e32-4b4b-9068-cfffb926c4bd,325560.0
41,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,5,Bad Day,a0238504-59f9-44a9-915b-f81f6afa98af,264600.0
42,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,6,Sing,4a9a98da-581b-419f-8f02-9c01cc94eb9b,360933.0
43,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,7,There’s No Other Way,f2903d45-03c8-4631-a1e1-3d0d33c57cbe,203840.0
44,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,8,Fool,5234f29d-777c-480b-bb47-d42c922a80ac,195333.0
45,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,9,Come Together,27090003-009c-4337-a648-7483c36bbfff,232400.0
46,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,10,High Cool,c3820526-1b1d-4852-b8ee-9fb909ddafb0,217626.0
47,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,11,Birthday,0b9b5669-eef0-420a-b695-350b36219c62,230000.0
48,ba853904-ae25-4ebb-89d6-c44cfbd71bd2,Blur,6ef2736f-e68b-3512-97e5-0b5003fd3d9a,Leisure,21973b4f-dbad-3d78-bfb6-edcbc97d480e,Leisure,1991,CA,CD,12,Wear Me Down,a4f6872f-ff57-476c-8897-3ddc52d2169b,289333.0
49,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,1,Bored,02a5e8e3-2b6e-4c58-b4c1-cf54532c6dce,246360.0
50,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,2,Minus Blindfold,fd3c748f-64b4-4ff6-b7de-d6793de0c62d,244306.0
51,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,3,One Weak,011697a8-ea3d-4c4f-8a75-2b703decf1f0,268893.0
52,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,4,Nosebleed,1da70975-2cbe-49e8-abc1-3fba89e26dc3,266106.0
53,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,5,Lifter,2f183e18-7b41-44dd-8f95-2a1f142cf840,283026.0
54,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,6,Root,2258241d-9037-4cf6-915b-f354dc6b49f5,221066.0
55,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,7,7 Words,3e146264-5159-48e5-8940-db20aa99f482,223866.0
56,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,8,Birthmark,c409b0f2-29c4-4d89-aaa5-21e8f3c8f1fc,258506.0
57,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,9,Engine No. 9,cd9311bb-3713-4ef1-b394-b54f7d8eeb95,205226.0
58,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,10,Fireal,9dab0525-0ae3-40c1-9ea4-649579c7dce7,395573.0
59,7527f6c2-d762-4b88-b5e2-9244f1e34c46,Deftones,0b4ea447-444c-34ba-ba87-96496f2e15b8,Adrenaline,68212754-e64a-3616-9a40-29cdbf2ba425,Adrenaline,1995-10-02,XE,CD,11,Fist,879ccf75-15db-420f-b568-4b256474bd12,215400.0

In [16]:
import time
time.sleep(15)

sp_id = "ba0d6274-db14-4ef5-b28d-657ebde1a396"

with open(f"../data/raw/artists/{sp_id}.json", "r", encoding="utf-8") as f:
    sp_data = json.load(f)

clean_albums = [
    rg for rg in sp_data["release-groups"]
    if rg.get("primary-type") == "Album" and not rg.get("secondary-types")
]
chosen_album = clean_albums[0]

releases = mb_client.get_releases_from_group(chosen_album["id"])
best_release = pick_best_release(releases)

release_detail = mb_client.get_release(best_release["id"], inc="recordings+media+artist-credits+labels")

rows = release_to_track_rows(
    release_detail=release_detail,
    artist_id=sp_id,
    artist_name="The Smashing Pumpkins",
    release_group_id=chosen_album["id"],
    release_group_title=chosen_album["title"]
)

all_rows.extend(rows)
print(f"The Smashing Pumpkins: {len(rows)} tracks added from '{chosen_album['title']}' ({best_release.get('date')})")

The Smashing Pumpkins: 10 tracks added from 'Gish' (1991)

In [17]:
print(len(all_rows))

70

In [18]:
album_tracks_df = pd.DataFrame(all_rows)
album_tracks_df.to_csv("../data/processed/album_tracks.csv", index=False)
album_tracks_df

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
0,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,1,Blew,2837e0d2-5ce9-44da-803e-797c835d672c,174133.0
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,2,Floyd the Barber,4cce1ee1-38e6-4ea0-8584-b6ebeb854d7d,137973.0
2,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,3,About a Girl,b2e623ea-378b-4479-bb75-fa202aacbfc9,168293.0
3,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,4,School,0b3292f6-8f0d-4160-92d3-49348029a619,162173.0
4,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,5,Love Buzz,1adfecb7-875f-4203-b3b1-8e2e643f94a2,215093.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,6,Suffer,d283e46e-28e3-4d0c-96f0-4c67089a97a3,311266.0
66,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,7,Snail,d611c71c-0551-4083-abfe-89426c80dab4,311000.0
67,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,8,Tristessa,90c44add-190e-4cc6-89db-ae9b9aeea745,213600.0
68,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,9,Window Paine,b3b0764b-9ccb-43fd-bb61-37abdcf0c051,351706.0
69,ba0d6274-db14-4ef5-b28d-657ebde1a396,The Smashing Pumpkins,4ac82f0b-1532-3734-80d7-5c02265197aa,Gish,4009d8ba-5f3d-3172-ab8b-1df53d83bfa6,Gish,1991,NL,CD,10,Daydream / I'm Going Crazy,39c23d3b-0e9c-4a78-8017-398d78668c37,187760.0