In [ ]:
import pandas as pd

In [4]:
df = pd.read_csv("../data/processed/album_tracks.csv")
print(df.shape)
print(df.dtypes)

(70, 13)
artist_id                  str
artist_name                str
release_group_id           str
release_group_title        str
release_id                 str
release_title              str
release_date               str
country                    str
medium_format              str
track_position           int64
track_title                str
recording_id               str
length_ms              float64
dtype: object

In [7]:
df.head(5)

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
0,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,1,Blew,2837e0d2-5ce9-44da-803e-797c835d672c,174133.0
1,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,2,Floyd the Barber,4cce1ee1-38e6-4ea0-8584-b6ebeb854d7d,137973.0
2,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,3,About a Girl,b2e623ea-378b-4479-bb75-fa202aacbfc9,168293.0
3,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,4,School,0b3292f6-8f0d-4160-92d3-49348029a619,162173.0
4,5b11f4ce-a62d-471e-81fc-a69a8278c7da,Nirvana,f1afec0b-26dd-3db5-9aa1-c91229a74a24,Bleach,02b23593-ad18-4c8c-b30a-5c96b4796289,Bleach,1989,CA,CD,5,Love Buzz,1adfecb7-875f-4203-b3b1-8e2e643f94a2,215093.0

In [5]:
print(df.head())

                              artist_id artist_name  \
0  5b11f4ce-a62d-471e-81fc-a69a8278c7da     Nirvana
1  5b11f4ce-a62d-471e-81fc-a69a8278c7da     Nirvana
2  5b11f4ce-a62d-471e-81fc-a69a8278c7da     Nirvana
3  5b11f4ce-a62d-471e-81fc-a69a8278c7da     Nirvana
4  5b11f4ce-a62d-471e-81fc-a69a8278c7da     Nirvana

                       release_group_id release_group_title  \
0  f1afec0b-26dd-3db5-9aa1-c91229a74a24              Bleach
1  f1afec0b-26dd-3db5-9aa1-c91229a74a24              Bleach
2  f1afec0b-26dd-3db5-9aa1-c91229a74a24              Bleach
3  f1afec0b-26dd-3db5-9aa1-c91229a74a24              Bleach
4  f1afec0b-26dd-3db5-9aa1-c91229a74a24              Bleach

                             release_id release_title release_date country  \
0  02b23593-ad18-4c8c-b30a-5c96b4796289        Bleach         1989      CA
1  02b23593-ad18-4c8c-b30a-5c96b4796289        Bleach         1989      CA
2  02b23593-ad18-4c8c-b30a-5c96b4796289        Bleach         1989      CA
3  02b23593-ad18-4c8c-b30a-5c96b4796289        Bleach         1989      CA
4  02b23593-ad18-4c8c-b30a-5c96b4796289        Bleach         1989      CA

  medium_format  track_position       track_title  \
0            CD               1              Blew
1            CD               2  Floyd the Barber
2            CD               3      About a Girl
3            CD               4            School
4            CD               5         Love Buzz

                           recording_id  length_ms
0  2837e0d2-5ce9-44da-803e-797c835d672c   174133.0
1  4cce1ee1-38e6-4ea0-8584-b6ebeb854d7d   137973.0
2  b2e623ea-378b-4479-bb75-fa202aacbfc9   168293.0
3  0b3292f6-8f0d-4160-92d3-49348029a619   162173.0
4  1adfecb7-875f-4203-b3b1-8e2e643f94a2   215093.0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   artist_id            70 non-null     str
 1   artist_name          70 non-null     str
 2   release_group_id     70 non-null     str
 3   release_group_title  70 non-null     str
 4   release_id           70 non-null     str
 5   release_title        70 non-null     str
 6   release_date         70 non-null     str
 7   country              70 non-null     str
 8   medium_format        70 non-null     str
 9   track_position       70 non-null     int64
 10  track_title          70 non-null     str
 11  recording_id         70 non-null     str
 12  length_ms            69 non-null     float64
dtypes: float64(1), int64(1), str(11)
memory usage: 7.2 KB

In [9]:
pd.isnull(df).sum()

artist_id              0
artist_name            0
release_group_id       0
release_group_title    0
release_id             0
release_title          0
release_date           0
country                0
medium_format          0
track_position         0
track_title            0
recording_id           0
length_ms              1
dtype: int64

In [10]:
print(df.duplicated().sum())
print(df.duplicated(subset=["recording_id"]).sum())

0
0

In [11]:
df.nunique()

artist_id               6
artist_name             6
release_group_id        6
release_group_title     6
release_id              6
release_title           6
release_date            4
country                 4
medium_format           2
track_position         13
track_title            70
recording_id           70
length_ms              68
dtype: int64

In [13]:
df[df["length_ms"].isnull()]

,artist_id,artist_name,release_group_id,release_group_title,release_id,release_title,release_date,country,medium_format,track_position,track_title,recording_id,length_ms
23,83b9cbe7-9857-49e2-ab8e-b57b01038103,Pearl Jam,cea5d18a-1924-3cda-bebc-38933834b25d,Ten,4cafa0e6-8ba5-40c6-ba63-7e49b5be6432,Ten,1991,US,"12"" Vinyl",11,Release,d42f73ee-68c4-4c4d-9dbc-206979c53e7d,NaN

Pearl Jam - Ten - track 11 "Release" has missing length_ms in the selected MusicBrainz release edition.
This is kept as missing for now because duration is not critical for graph schema design.

In [15]:
df[["artist_name", "release_group_title", "release_date"]].drop_duplicates()

              artist_name release_group_title release_date
0                 Nirvana              Bleach         1989
13              Pearl Jam                 Ten         1991
24            Soundgarden        Ultramega OK   1988-10-31
37                   Blur             Leisure         1991
49               Deftones          Adrenaline   1995-10-02
60  The Smashing Pumpkins                Gish         1991

In [26]:
df["length_min"] = df["length_ms"] / 60000
df[["track_title", "length_ms", "length_min"]].head()

        track_title  length_ms  length_min
0              Blew   174133.0    2.902217
1  Floyd the Barber   137973.0    2.299550
2      About a Girl   168293.0    2.804883
3            School   162173.0    2.702883
4         Love Buzz   215093.0    3.584883

In [41]:
album_summary = (
    df.groupby(["artist_name", "release_group_title", "release_date", "country", "medium_format"])
    .agg(
        track_count=("recording_id", "count"),
        avg_track_length_min=("length_min", "mean"),
        total_album_length_min=("length_min", "sum")
    )
    .reset_index()
)

album_summary

,artist_name,release_group_title,release_date,country,medium_format,track_count,avg_track_length_min,total_album_length_min
0,Blur,Leisure,1991,CA,CD,12,4.185496,50.225950
1,Deftones,Adrenaline,1995-10-02,XE,CD,11,4.285345,47.138800
2,Nirvana,Bleach,1989,CA,CD,13,3.286201,42.720617
3,Pearl Jam,Ten,1991,US,"12"" Vinyl",11,4.431772,44.317717
4,Soundgarden,Ultramega OK,1988-10-31,US,CD,13,3.292950,42.808350
5,The Smashing Pumpkins,Gish,1991,NL,CD,10,4.631662,46.316617

In [42]:
df.describe()

       track_position      length_ms  length_min
count       70.000000      69.000000   69.000000
mean         6.385714  237850.478261    3.964175
std          3.469506   72551.282394    1.209188
min          1.000000   61866.000000    1.031100
25%          3.250000  199906.000000    3.331767
50%          6.000000  231893.000000    3.864883
75%          9.000000  284733.000000    4.745550
max         13.000000  395573.000000    6.592883

In [24]:
df.groupby(["artist_name", "release_group_title"])["recording_id"].count().sort_values(ascending=False)

artist_name            release_group_title
Soundgarden            Ultramega OK           13
Nirvana                Bleach                 13
Blur                   Leisure                12
Deftones               Adrenaline             11
Pearl Jam              Ten                    11
The Smashing Pumpkins  Gish                   10
Name: recording_id, dtype: int64

In [43]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique")

artist_id: 6 unique
artist_name: 6 unique
release_group_id: 6 unique
release_group_title: 6 unique
release_id: 6 unique
release_title: 6 unique
release_date: 4 unique
country: 4 unique
medium_format: 2 unique
track_position: 13 unique
track_title: 70 unique
recording_id: 70 unique
length_ms: 68 unique
length_min: 68 unique

## Album-level EDA Insight

The dataset currently contains 6 selected studio albums from 6 seed artists, with 70 total recordings/tracks. Each album contains between 10 and 13 tracks, which suggests that the release selection strategy produced clean album-level data rather than noisy deluxe editions or compilations.

Album duration ranges from around 42 to 50 minutes. Pearl Jam's `Ten` has one missing track length, so its total duration is slightly underestimated.

For the future graph schema, this EDA supports a basic hierarchical structure:

Artist -> ReleaseGroup/Album -> Release -> Recording

At this stage, `release_date`, `country`, `medium_format`, `track_position`, and `length_min` are better modeled as properties rather than separate nodes.

## Graph Schema EDA Notes

Current CSV row meaning:
Each row represents one recording/track inside one selected release of one release group by one artist.

Candidate nodes:
- Artist
- ReleaseGroup / Album
- Release
- Recording / Track

Candidate relationships:
- Artist -> ReleaseGroup
- ReleaseGroup -> Release
- Release -> Recording

Candidate properties:
- release_date
- country
- medium_format
- track_position
- length_ms / length_min

In [32]:
df[["artist_name", "release_group_title", "release_title", "country", "medium_format", "release_date"]].drop_duplicates()

,artist_name,release_group_title,release_title,country,medium_format,release_date
0,Nirvana,Bleach,Bleach,CA,CD,1989
13,Pearl Jam,Ten,Ten,US,"12"" Vinyl",1991
24,Soundgarden,Ultramega OK,Ultramega OK,US,CD,1988-10-31
37,Blur,Leisure,Leisure,CA,CD,1991
49,Deftones,Adrenaline,Adrenaline,XE,CD,1995-10-02
60,The Smashing Pumpkins,Gish,Gish,NL,CD,1991

## Release Edition Metadata Check

The `country` and `medium_format` fields appear to describe the selected MusicBrainz release edition, not the artist's origin or the album's cultural/geographic origin.

For example, `Bleach` by Nirvana is associated with `CA`, and `Gish` by The Smashing Pumpkins is associated with `NL`. These values should not be interpreted as artist origin countries.

Therefore, in the future graph schema, `country` and `medium_format` should be modeled as properties of the `Release` node, not as separate `Country` nodes connected to `Artist`.

Candidate modeling decision:

Artist -> ReleaseGroup/Album -> Release -> Recording

Release properties:
- release_date
- country
- medium_format

In [33]:
df.sort_values(["artist_name", "track_position"])[
    ["artist_name", "release_group_title", "track_position", "track_title"]
]

,artist_name,release_group_title,track_position,track_title
37,Blur,Leisure,1,She’s So High
38,Blur,Leisure,2,Bang
39,Blur,Leisure,3,Slow Down
40,Blur,Leisure,4,Repetition
41,Blur,Leisure,5,Bad Day
...,...,...,...,...
65,The Smashing Pumpkins,Gish,6,Suffer
66,The Smashing Pumpkins,Gish,7,Snail
67,The Smashing Pumpkins,Gish,8,Tristessa
68,The Smashing Pumpkins,Gish,9,Window Paine
69,The Smashing Pumpkins,Gish,10,Daydream / I'm Going Crazy

In [34]:
for album, group in df.groupby("release_group_title"):
    positions = group["track_position"].tolist()
    print(album, positions)

Adrenaline [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Bleach [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
Gish [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Leisure [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Ten [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Ultramega OK [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [37]:
df.columns.tolist()

['artist_id',
 'artist_name',
 'release_group_id',
 'release_group_title',
 'release_id',
 'release_title',
 'release_date',
 'country',
 'medium_format',
 'track_position',
 'track_title',
 'recording_id',
 'length_ms',
 'length_min']

In [38]:
relationship_cols = [
    "artist_name",
    "release_group_title",
    "release_title",
    "track_title",
    "country",
    "medium_format"
]

df[relationship_cols].head()

,artist_name,release_group_title,release_title,track_title,country,medium_format
0,Nirvana,Bleach,Bleach,Blew,CA,CD
1,Nirvana,Bleach,Bleach,Floyd the Barber,CA,CD
2,Nirvana,Bleach,Bleach,About a Girl,CA,CD
3,Nirvana,Bleach,Bleach,School,CA,CD
4,Nirvana,Bleach,Bleach,Love Buzz,CA,CD

## Relationship Richness Check

The current `album_tracks.csv` mainly represents a hierarchical music structure:

Artist -> ReleaseGroup/Album -> Release -> Recording

From the available columns, the dataset can describe which tracks belong to which release and artist. However, it does not yet contain richer cross-artist relationships such as shared members, shared producers, shared labels, tags/genres, or artist-to-artist relationships.

This means the current CSV is useful for validating the ingestion pipeline and designing the basic graph structure, but it is not yet enough to fully demonstrate why graph retrieval may outperform vector retrieval.

## Phase 3 Interim Conclusion

The current dataset is clean and structurally consistent. It contains 6 seed artists, 6 selected studio albums, and 70 unique recordings/tracks.

Genre/tag distribution is not analyzed in this phase because `album_tracks.csv` does not yet include genre or tag fields. Tags are planned as candidate relationship-rich metadata for the next graph design phase.

The EDA supports a basic graph schema:

Artist → ReleaseGroup/Album → Release → Recording

However, this structure is mostly hierarchical and does not yet capture the relationship-rich data that makes Knowledge Graph retrieval valuable. For Phase 4, the graph design should incorporate richer MusicBrainz relationships such as artist relationships, member-of relationships, label relationships, and possibly tags/genres.

Therefore, the next design question is not only “How do we represent albums and tracks?”, but “What relationships allow graph traversal to discover connections that vector retrieval may miss?”