In [1]:
import pandas as pd
from pathlib import Path

In [2]:
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

vector_path = PROJECT_ROOT / "data" / "processed" / "vector_retrieval_results.csv"
graph_path = PROJECT_ROOT / "data" / "processed" / "graph_retrieval_results.csv"

vector_results = pd.read_csv(vector_path)
graph_results = pd.read_csv(graph_path)

vector_results.head(), graph_results.head()

(  query_artist  rank retrieved_artist  similarity_score
 0  Soundgarden     1        Pearl Jam          0.740760
 1  Soundgarden     2          Nirvana          0.711962
 2  Soundgarden     3             Blur          0.684405
 3      Nirvana     1        Pearl Jam          0.754655
 4      Nirvana     2      Soundgarden          0.711962,
   query_artist  rank       retrieved_artist  graph_score evidence_type  \
 0         Blur     1              Pearl Jam            7    shared_tag
 1         Blur     2  The Smashing Pumpkins            5    shared_tag
 2         Blur     3                Nirvana            4    shared_tag
 3     Deftones     1            Soundgarden            2    shared_tag
 4     Deftones     2                Nirvana            2    shared_tag

                                             evidence
 0  ['alternative rock', 'grunge', 'rock', 'art ro...
 1  ['alternative rock', 'grunge', 'rock', 'shoega...
 2  ['alternative rock', 'grunge', 'noise rock', '...
 3          ['alternative metal', 'alternative rock']
 4          ['alternative metal', 'alternative rock']  )

In [ ]:
print("Vector columns:", vector_results.columns.tolist())
print("Graph columns:", graph_results.columns.tolist())

Vector columns: ['query_artist', 'rank', 'retrieved_artist', 'similarity_score']
Graph columns: ['query_artist', 'rank', 'retrieved_artist', 'graph_score', 'evidence_type', 'evidence']

In [7]:
def compare_artist(query_artist):
    vector_view = vector_results[
        vector_results["query_artist"] == query_artist
    ].copy()

    vector_view["retrieval_type"] = "vector"
    vector_view["score"] = vector_view["similarity_score"]
    vector_view["evidence_type"] = "-"
    vector_view["evidence"] = "-"

    vector_view = vector_view[
        [
            "query_artist",
            "retrieval_type",
            "rank",
            "retrieved_artist",
            "score",
            "evidence_type",
            "evidence"
        ]
    ]

    graph_view = graph_results[
        graph_results["query_artist"] == query_artist
    ].copy()

    graph_view["retrieval_type"] = "graph"
    graph_view["score"] = graph_view["graph_score"]

    graph_view = graph_view[
        [
            "query_artist",
            "retrieval_type",
            "rank",
            "retrieved_artist",
            "score",
            "evidence_type",
            "evidence"
        ]
    ]

    comparison = pd.concat([vector_view, graph_view], ignore_index=True)

    return comparison

In [14]:
graph_results.groupby("evidence_type")["graph_score"].describe()

               count      mean       std  min  25%  50%  75%  max
evidence_type
shared_member    4.0  1.000000  0.000000  1.0  1.0  1.0  1.0  1.0
shared_tag      18.0  4.444444  1.885618  2.0  3.0  4.0  6.0  7.0

In [8]:
compare_artist("Pearl Jam")

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,Pearl Jam,vector,1,Blur,0.760920,-,-
1,Pearl Jam,vector,2,Nirvana,0.754655,-,-
2,Pearl Jam,vector,3,Soundgarden,0.740760,-,-
3,Pearl Jam,graph,1,Soundgarden,1.000000,shared_member,['Matt Cameron']
4,Pearl Jam,graph,1,Nirvana,7.000000,shared_tag,"['alternative rock', 'grunge', 'usa', 'acousti..."
5,Pearl Jam,graph,2,Blur,7.000000,shared_tag,"['alternative rock', 'grunge', 'rock', 'art ro..."
6,Pearl Jam,graph,3,Soundgarden,4.000000,shared_tag,"['alternative rock', 'grunge', 'hard rock', 'u..."

In [12]:
for artist in sorted(vector_results["query_artist"].unique()):
    print(f"\n -- {artist} --")
    display(compare_artist(artist))

 -- Blur --

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,Blur,vector,1,Pearl Jam,0.760920,-,-
1,Blur,vector,2,The Smashing Pumpkins,0.696780,-,-
2,Blur,vector,3,Deftones,0.691868,-,-
3,Blur,graph,1,Pearl Jam,7.000000,shared_tag,"['alternative rock', 'grunge', 'rock', 'art ro..."
4,Blur,graph,2,The Smashing Pumpkins,5.000000,shared_tag,"['alternative rock', 'grunge', 'rock', 'shoega..."
5,Blur,graph,3,Nirvana,4.000000,shared_tag,"['alternative rock', 'grunge', 'noise rock', '..."

 -- Deftones --

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,Deftones,vector,1,Blur,0.691868,-,-
1,Deftones,vector,2,Soundgarden,0.681798,-,-
2,Deftones,vector,3,Pearl Jam,0.653498,-,-
3,Deftones,graph,1,Soundgarden,2.000000,shared_tag,"['alternative metal', 'alternative rock']"
4,Deftones,graph,2,Nirvana,2.000000,shared_tag,"['alternative metal', 'alternative rock']"
5,Deftones,graph,3,The Smashing Pumpkins,2.000000,shared_tag,"['alternative rock', 'shoegaze']"

 -- Nirvana --

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,Nirvana,vector,1,Pearl Jam,0.754655,-,-
1,Nirvana,vector,2,Soundgarden,0.711962,-,-
2,Nirvana,vector,3,Blur,0.675207,-,-
3,Nirvana,graph,1,Soundgarden,1.000000,shared_member,['Jason Everman']
4,Nirvana,graph,1,Pearl Jam,7.000000,shared_tag,"['alternative rock', 'grunge', 'usa', 'acousti..."
5,Nirvana,graph,2,Soundgarden,6.000000,shared_tag,"['alternative metal', 'alternative rock', 'ame..."
6,Nirvana,graph,3,Blur,4.000000,shared_tag,"['alternative rock', 'grunge', 'noise rock', '..."

 -- Pearl Jam --

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,Pearl Jam,vector,1,Blur,0.760920,-,-
1,Pearl Jam,vector,2,Nirvana,0.754655,-,-
2,Pearl Jam,vector,3,Soundgarden,0.740760,-,-
3,Pearl Jam,graph,1,Soundgarden,1.000000,shared_member,['Matt Cameron']
4,Pearl Jam,graph,1,Nirvana,7.000000,shared_tag,"['alternative rock', 'grunge', 'usa', 'acousti..."
5,Pearl Jam,graph,2,Blur,7.000000,shared_tag,"['alternative rock', 'grunge', 'rock', 'art ro..."
6,Pearl Jam,graph,3,Soundgarden,4.000000,shared_tag,"['alternative rock', 'grunge', 'hard rock', 'u..."

 -- Soundgarden --

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,Soundgarden,vector,1,Pearl Jam,0.740760,-,-
1,Soundgarden,vector,2,Nirvana,0.711962,-,-
2,Soundgarden,vector,3,Blur,0.684405,-,-
3,Soundgarden,graph,1,Nirvana,1.000000,shared_member,['Jason Everman']
4,Soundgarden,graph,2,Pearl Jam,1.000000,shared_member,['Matt Cameron']
5,Soundgarden,graph,1,Nirvana,6.000000,shared_tag,"['alternative metal', 'alternative rock', 'ame..."
6,Soundgarden,graph,2,Pearl Jam,4.000000,shared_tag,"['alternative rock', 'grunge', 'hard rock', 'u..."
7,Soundgarden,graph,3,The Smashing Pumpkins,2.000000,shared_tag,"['alternative rock', 'grunge']"

 -- The Smashing Pumpkins --

,query_artist,retrieval_type,rank,retrieved_artist,score,evidence_type,evidence
0,The Smashing Pumpkins,vector,1,Blur,0.696780,-,-
1,The Smashing Pumpkins,vector,2,Pearl Jam,0.663584,-,-
2,The Smashing Pumpkins,vector,3,Nirvana,0.629098,-,-
3,The Smashing Pumpkins,graph,1,Blur,5.000000,shared_tag,"['alternative rock', 'grunge', 'rock', 'shoega..."
4,The Smashing Pumpkins,graph,2,Nirvana,3.000000,shared_tag,"['alternative rock', 'grunge', 'rock']"
5,The Smashing Pumpkins,graph,3,Pearl Jam,3.000000,shared_tag,"['alternative rock', 'grunge', 'rock']"

#### Phase 9A Conclusion

This notebook compares the vector retrieval baseline and the graph retrieval baseline.

The vector retriever ranks artists based on embedding similarity from album and tag text. Its score is a cosine similarity value, where higher values mean the artist embeddings are more similar.

The graph retriever ranks artists based on explicit MusicBrainz graph evidence, such as shared members and shared tags. Its graph score is not a normalized similarity score. Instead, it represents the number of graph evidence items found for each relationship type.

Because of this, vector scores and graph scores should not be interpreted on the same scale. A vector score close to 1 means high embedding similarity, while a graph score of 1 shared member can still be meaningful because it represents direct historical relationship evidence.

One important example is Pearl Jam. The vector retriever ranks Blur highest for Pearl Jam based on text/tag similarity, while the graph retriever surfaces Soundgarden through Matt Cameron as shared-member evidence. This shows that graph retrieval can reveal historical or relational music connections that may not be ranked highest by vector similarity alone.

Overall, this comparison supports the main project idea: vector retrieval is useful for style/tag similarity, while graph retrieval is useful for relationship-based discovery.

The next step is to design a simple hybrid retrieval approach that combines vector similarity with graph-based evidence.